# Gradle properties.
# JVM args for the Gradle daemon.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Use the new incremental/non-incremental dexing.
android.useAndroidX=true

# Kotlin code style for this project.
kotlin.code.style=official

# Enable non-transitive R class.
android.nonTransitiveRClass=true
